### ISSUE TITLE
[gas-oracle][consensys-4.2]: Unexpected Price Query Return Value and Single Point of Failure

### ISSUE THREAD

**Issue by byteflyfunny** [mantlenetworkio/mantle#1054]
Query() ignores the error indicator. Therefore, the returned price can be nil, which may be unexpected to the caller, potentially causing an exception.
`result, ok := response.Result().(*Result)
if !ok {
	return nil, fmt.Errorf("cannot parse result")
}
if result.Result.Price == "" {
	return nil, fmt.Errorf("empty price")
}
bigPrice, _ := big.NewFloat(0).SetString(result.Result.Price)
return bigPrice, nil`

**Comment by Tri-stone** [comment]
We have implemented the following approaches to address the issue of a single token ratio source:

1. In addition to centralized exchanges, we have added `Uniswap V3` as an additional ratio source.

2. We have set reasonable upper and lower bounds for the exchange rate to exclude outliers. The returned exchange rate must be within this range, otherwise a default value will be returned. Any exchange rate outside the range will be considered an outlier, and the default `eth_price` is $1800, the default `mnt_price` is $0.45 and the default `token_ratio` is 4000.

3. When requesting the exchange rate, we make simultaneous requests to both rate sources:
    
    3.1. If both rate requests fail, we have a default value to handle unexpected situations. For example, if the eth_price is $1800 and the token_ratio is 4000.
   
    3.2 If both rate requests return valid values, we use the average of the two rates.
    
    3.3 If only one rate source returns a valid value, we use that value as the exchange rate.
